name: pro_health_360
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  afya_moja_core: ^0.2.4
  app_wrapper: ^0.1.35
  async_redux: ^15.0.0
  collection: ^1.16.0
  connectivity_plus: ^2.3.5
  debug_logger: ^0.0.23
  device_info: ^2.0.3
  double_back_to_close_app: ^2.1.0
  firebase_analytics: ^9.1.12
  firebase_core: ^1.19.1
  firebase_messaging: ^11.4.4
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  flutter_graphql_client: ^0.1.23
  flutter_html: ^3.0.0-alpha.5
  flutter_image_compress: ^1.0.0
  flutter_local_notifications: ^9.6.1
  flutter_local_notifications_platform_interface: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.2.1
  flutter_svg: ^1.1.1+1
  freezed: ^2.0.3
  freezed_annotation: ^2.0.3
  google_fonts: 2.2.0
  html: ^0.15.0
  http: ^0.13.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  launch_review: ^3.0.1
  path: ^1.8.1
  path_provider: ^2.0.11
  pin_code_text_field: ^1.8.0
  platform: ^3.1.0
  plugin_platform_interface: ^2.0.2
  quiver: ^3.0.1+1
  rxdart: ^0.27.4
  sentry_flutter: ^6.6.2
  share: ^2.0.4
  shared_preferences: ^2.0.15
  shared_themes: ^0.1.4
  shimmer: ^2.0.0
  sqflite: ^2.0.2+1
  stream_chat_flutter: ^4.3.0
  transparent_image: ^2.0.0
  uni_links: ^0.5.1
  unicons: ^2.1.0
  url_launcher: ^6.1.4
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.11
  connectivity_plus_platform_interface: ^1.2.1
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  mockito: ^5.2.0
  mocktail_image_network: ^0.3.1

flutter:
  fonts:
    - family: Sora
      fonts:
        - asset: fonts/Sora/Sora-Bold.ttf
        - asset: fonts/Sora/Sora-ExtraBold.ttf
        - asset: fonts/Sora/Sora-ExtraLight.ttf
        - asset: fonts/Sora/Sora-Light.ttf
        - asset: fonts/Sora/Sora-Medium.ttf
        - asset: fonts/Sora/Sora-Regular.ttf
        - asset: fonts/Sora/Sora-SemiBold.ttf
        - asset: fonts/Sora/Sora-Thin.ttf
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/
    - packages/afya_moja_core/assets/ken.png
    - packages/afya_moja_core/assets/tza.png
    - packages/afya_moja_core/assets/uga.png
    - packages/afya_moja_core/assets/usa.png
    - packages/afya_moja_core/assets/gbr.png
    - packages/afya_moja_core/assets/bel.png
    - packages/afya_moja_core/assets/nga.png
